# Generated by Django 4.2.1 on 2023-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('patent_name', models.CharField(max_length=255)),
                ('attached_file', models.FileField(upload_to='media/')),
                ('application_type', models.CharField(choices=[('invention', 'Патент на изобретение'), ('trademark', 'Регистрация товарного знака')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
