# Generated by Django 4.2.1 on 2023-06-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_category_post_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted', 'title'], 'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
    ]
